import { useEffect, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getChronologyStatusApi, startChronologyGenerationApi } from "@/api/chronology";
import { delayEventsKey } from "./useDelayEvents";

export const chronologyStatusKey = (projectId: string) =>
  ["chronology-status", projectId] as const;

// Projects whose chronology was auto-generated this session — prevents the auto
// trigger from firing repeatedly.
const autoGenerated = new Set<string>();

/**
 * Drives AI chronology generation for the Chronology tab. The generation runs in
 * the background on the server (reasoning over the whole data room), so this hook:
 *   - polls the generation status while it runs,
 *   - refreshes the delay-events list when a run finishes (chronology lives on the
 *     events),
 *   - auto-starts a run once the project has delay events but none of them has a
 *     chronology yet,
 *   - exposes `start()` for the manual "Generate with AI" button.
 */
export function useChronologyGenerator(
  projectId: string,
  eventsLoaded: boolean,
  eventCount: number,
  chronologyCount: number,
) {
  const qc = useQueryClient();

  const statusQ = useQuery({
    queryKey: chronologyStatusKey(projectId),
    queryFn: () => getChronologyStatusApi(projectId),
    enabled: !!projectId,
    refetchInterval: (query) => (query.state.data?.status === "running" ? 3000 : false),
  });

  const start = useMutation({
    mutationFn: () => startChronologyGenerationApi(projectId),
    onSuccess: (s) => qc.setQueryData(chronologyStatusKey(projectId), s),
  });

  const status = statusQ.data?.status;

  // When a run transitions out of "running", refresh the events (chronology is
  // stored on each delay event).
  const prevStatus = useRef<string | undefined>(undefined);
  useEffect(() => {
    if (prevStatus.current === "running" && (status === "done" || status === "failed")) {
      qc.invalidateQueries({ queryKey: delayEventsKey(projectId) });
    }
    prevStatus.current = status;
  }, [status, projectId, qc]);

  // Auto-generate once: events exist but none has a chronology yet.
  useEffect(() => {
    if (!projectId || !eventsLoaded || eventCount === 0 || chronologyCount > 0) return;
    if (statusQ.isLoading || status === "running" || start.isPending) return;
    if (autoGenerated.has(projectId)) return;

    autoGenerated.add(projectId);
    start.mutate(undefined, { onError: () => autoGenerated.delete(projectId) });
  }, [projectId, eventsLoaded, eventCount, chronologyCount, status, statusQ.isLoading, start]);

  const isRunning = status === "running" || start.isPending;
  const error = status === "failed" ? statusQ.data?.error || "AI chronology generation failed." : "";
  return { isRunning, error, start: () => start.mutate() };
}
