"""Admissibility scoring-matrix store + background generation (Admissibility tab).

One row per project. The matrix is generated by AI from the project's delay
events and Clause Library, which takes too long for an HTTP request — so
generation runs in the background and the row's `status` is polled by the UI.
The analyst can also edit the matrix; edits save straight to `content`.
"""
import asyncio
import os
import uuid
from datetime import datetime, timezone
from typing import Dict

import anthropic

from app.db import SessionLocal
from app.models import AdmissibilityAssessment
from app.services import delay_event_service, project_clause_service, project_service
from app.services.ai_service import MODEL, generate_admissibility_assessment

_sem = asyncio.Semaphore(int(os.getenv("CLAIM_CONCURRENCY", "2")))

_NOT_CONFIGURED = (
    "AI analysis is not configured — set ANTHROPIC_API_KEY in apps/backend/.env "
    "and restart the backend."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def get(project_id: str) -> Dict:
    """Return the stored assessment + status (idle shape if none yet)."""
    with SessionLocal() as db:
        row = db.get(AdmissibilityAssessment, project_id)
        return row.to_dict() if row else {
            "projectId": project_id, "content": None, "model": None,
            "status": "", "error": None, "updatedAt": None,
        }


def _set(project_id: str, **fields) -> None:
    with SessionLocal() as db:
        row = db.get(AdmissibilityAssessment, project_id)
        if not row:
            row = AdmissibilityAssessment(projectId=project_id, createdAt=_now())
            db.add(row)
        for k, v in fields.items():
            setattr(row, k, v)
        row.updatedAt = _now()
        db.commit()


def mark_running(project_id: str) -> None:
    _set(project_id, status="running", error=None)


def _assign_ids(content: Dict) -> Dict:
    """Give every clause and criterion a stable id so the UI can key + edit rows."""
    clauses = []
    for cl in (content or {}).get("clauses", []) or []:
        cl = dict(cl)
        cl["id"] = cl.get("id") or f"acl-{uuid.uuid4().hex[:8]}"
        criteria = []
        for cr in cl.get("criteria", []) or []:
            cr = dict(cr)
            cr["id"] = cr.get("id") or f"acr-{uuid.uuid4().hex[:8]}"
            criteria.append(cr)
        cl["criteria"] = criteria
        clauses.append(cl)
    return {"clauses": clauses, "summary": (content or {}).get("summary", "")}


def save_content(project_id: str, content: Dict) -> Dict:
    """Persist an analyst-edited matrix; ensures ids on any newly-added rows."""
    _set(project_id, content=_assign_ids(content), status="done", error=None)
    return get(project_id)


def _load(project_id: str):
    """Blocking: gather project, delay events and the clause library (run in a thread)."""
    project = project_service.get_project(project_id)
    events = delay_event_service.list_by_project(project_id)
    clauses = project_clause_service.list_by_project(project_id)
    return project, events, clauses


async def run_generation(project_id: str) -> None:
    """Generate the admissibility matrix in the background and store it."""
    async with _sem:
        _set(project_id, status="running", error=None)
        try:
            if not os.getenv("ANTHROPIC_API_KEY"):
                _set(project_id, status="failed", error=_NOT_CONFIGURED)
                return
            project, events, clauses = await asyncio.to_thread(_load, project_id)
            if not project:
                _set(project_id, status="failed", error="Project not found.")
                return
            if not events and not clauses:
                _set(
                    project_id,
                    status="failed",
                    error="Add delay events or a clause library first — the matrix is built from them.",
                )
                return

            content = await generate_admissibility_assessment(
                events=events,
                clauses=clauses,
                project_name=project.get("name"),
                standard=project.get("standard"),
            )
            _set(project_id, content=_assign_ids(content), model=MODEL, status="done", error=None)
        except anthropic.AuthenticationError:
            _set(project_id, status="failed", error=_NOT_CONFIGURED)
        except anthropic.APIStatusError as e:
            _set(project_id, status="failed", error=f"AI provider error ({e.status_code}).")
        except Exception as e:  # noqa: BLE001
            _set(project_id, status="failed", error=str(e)[:500])
