"""Client proposal store + background generation (Proposals → Proposal tab).

The costed client proposal is generated by AI from the proposal's identified
delay events and documents. Generation takes too long for an HTTP request, so it
runs in the background and the row's `status` is polled by the UI. Mirrors
eot_claim_service, but produces the client-facing costed proposal instead of the
EOT claim.
"""
import asyncio
import os
from datetime import datetime, timezone
from typing import Dict

import anthropic

from app.db import SessionLocal
from app.models import ClientProposal
from app.services import delay_event_service, document_service, project_service
from app.services.ai_service import MODEL, generate_client_proposal

_sem = asyncio.Semaphore(int(os.getenv("PROPOSAL_CONCURRENCY", "2")))

_NOT_CONFIGURED = (
    "AI analysis is not configured — set ANTHROPIC_API_KEY in apps/backend/.env "
    "and restart the backend."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_proposal(project_id: str) -> Dict:
    """Return the stored proposal + status (idle shape if none yet)."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        return row.to_dict() if row else {
            "projectId": project_id, "content": None, "model": None,
            "status": "", "error": None, "updatedAt": None,
            "sentToClient": False, "sentAt": None,
        }


def _set(project_id: str, **fields) -> None:
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if not row:
            row = ClientProposal(projectId=project_id, createdAt=_now())
            db.add(row)
        for k, v in fields.items():
            setattr(row, k, v)
        row.updatedAt = _now()
        db.commit()


def mark_running(project_id: str) -> None:
    _set(project_id, status="running", error=None)


def mark_sent(project_id: str) -> Dict:
    """Flag the proposal as sent to the client. Returns the updated row."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if not row:
            return {"error": "Proposal not found"}
        if row.status != "done":
            return {"error": "Proposal must be generated before sending"}
        row.sentToClient = True
        row.sentAt = _now()
        row.updatedAt = _now()
        db.commit()
        return row.to_dict()


def save_inputs(project_id: str, inputs: Dict) -> Dict:
    """Store the admin-entered proposal fields (merged) and return the row."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if not row:
            row = ClientProposal(projectId=project_id, createdAt=_now())
            db.add(row)
        merged = dict(row.inputs or {})
        merged.update({k: v for k, v in (inputs or {}).items()})
        row.inputs = merged
        row.updatedAt = _now()
        db.commit()
        return row.to_dict()


def _to_number(v) -> float:
    """Parse an admin-entered amount ("1,200", "OMR 400", "") to a float."""
    import re
    s = re.sub(r"[^0-9.\-]", "", str(v or ""))
    try:
        return float(s) if s not in ("", "-", ".") else 0.0
    except ValueError:
        return 0.0


def _apply_admin_commercials(content: dict, inputs: dict) -> dict:
    """When the admin has priced the line items, use them verbatim as the costing
    (so the fees are exact, not AI-invented) and recompute the net total after any
    special discount."""
    items = (inputs or {}).get("lineItems") or []
    priced = [
        {
            "item": str(it.get("item", "")).strip(),
            "description": str(it.get("description", "")).strip(),
            "timeline": str(it.get("timeline", "")).strip(),
            "amount": _to_number(it.get("amount")),
        }
        for it in items
        if str(it.get("item", "")).strip() and str(it.get("amount", "")).strip()
    ]
    if not priced:
        return content

    costing = list(priced)
    total = sum(c["amount"] for c in priced)
    discount = _to_number((inputs or {}).get("discount"))
    if discount > 0:
        costing.append(
            {"item": "Less special discount", "description": "", "timeline": "", "amount": -discount}
        )
        total -= discount

    content = dict(content)
    content["costing"] = costing
    content["total"] = total
    return content


def _load(project_id: str):
    """Blocking: gather proposal record, events, document names and admin inputs."""
    project = project_service.get_project(project_id)
    events = delay_event_service.list_by_project(project_id)
    doc_names = [d.get("name", "") for d in document_service.list_by_project(project_id)]
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        inputs = dict(row.inputs) if row and row.inputs else {}
    return project, events, doc_names, inputs


async def run_generation(project_id: str) -> None:
    """Generate the costed client proposal in the background and store it."""
    async with _sem:
        _set(project_id, status="running", error=None)
        try:
            if not os.getenv("ANTHROPIC_API_KEY"):
                _set(project_id, status="failed", error=_NOT_CONFIGURED)
                return
            project, events, doc_names, inputs = await asyncio.to_thread(_load, project_id)
            if not project:
                _set(project_id, status="failed", error="Proposal not found.")
                return

            content = await generate_client_proposal(
                project=project, events=events, document_names=doc_names, inputs=inputs
            )
            # Admin-entered prices are authoritative — override the AI's costing.
            content = _apply_admin_commercials(content, inputs)
            _set(project_id, content=content, model=MODEL, status="done", error=None)
        except anthropic.AuthenticationError:
            _set(project_id, status="failed", error=_NOT_CONFIGURED)
        except anthropic.APIStatusError as e:
            _set(project_id, status="failed", error=f"AI provider error ({e.status_code}).")
        except Exception as e:  # noqa: BLE001
            _set(project_id, status="failed", error=str(e)[:500])
