"""Client proposal store + background generation (Proposals → Proposal tab).

The costed client proposal is generated by AI from the proposal's identified
delay events and documents. Generation takes too long for an HTTP request, so it
runs in the background and the row's `status` is polled by the UI. Mirrors
eot_claim_service, but produces the client-facing costed proposal instead of the
EOT claim.
"""
import asyncio
import os
import re
from datetime import datetime, timezone
from typing import Dict

import anthropic

from app.db import SessionLocal
from app.models import ClientProposal
from app.services import costing_service, delay_event_service, document_service, project_service
from app.services.ai_service import MODEL, generate_client_proposal

_sem = asyncio.Semaphore(int(os.getenv("PROPOSAL_CONCURRENCY", "2")))

_NOT_CONFIGURED = (
    "AI analysis is not configured — set ANTHROPIC_API_KEY in apps/backend/.env "
    "and restart the backend."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_proposal(project_id: str) -> Dict:
    """Return the stored proposal + status (idle shape if none yet)."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        return row.to_dict() if row else {
            "projectId": project_id, "content": None, "model": None,
            "status": "", "error": None, "updatedAt": None,
            "sentToClient": False, "sentAt": None,
        }


_REF_RE = re.compile(r"^AQMS/Proposal/(\d{2})/(\d+)$")


def _next_reference(db, yy: str) -> str:
    """The next free 'AQMS/Proposal/<yy>/<nn>' for the year, derived from the
    references already stored on other proposals."""
    used = {
        int(m.group(2))
        for (inputs,) in db.query(ClientProposal.inputs).all()
        if (m := _REF_RE.match(str((inputs or {}).get("reference") or "").strip()))
        and m.group(1) == yy
    }
    return f"AQMS/Proposal/{yy}/{(max(used) + 1) if used else 1:02d}"


def ensure_reference(project_id: str) -> Dict:
    """Return the proposal row, assigning it the next sequential AQMS reference if
    it doesn't have one yet, so the form opens with the number the proposal will be
    issued under. Persisted on first read so the number can't be handed out twice."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if row and str((row.inputs or {}).get("reference") or "").strip():
            return row.to_dict()
        if not row:
            row = ClientProposal(projectId=project_id, createdAt=_now())
            db.add(row)
        yy = datetime.now(timezone.utc).strftime("%y")
        row.inputs = {**(row.inputs or {}), "reference": _next_reference(db, yy)}
        row.updatedAt = _now()
        db.commit()
        return row.to_dict()


def _set(project_id: str, **fields) -> None:
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if not row:
            row = ClientProposal(projectId=project_id, createdAt=_now())
            db.add(row)
        for k, v in fields.items():
            setattr(row, k, v)
        row.updatedAt = _now()
        db.commit()


def mark_running(project_id: str) -> None:
    _set(project_id, status="running", error=None)


def mark_sent(project_id: str) -> Dict:
    """Flag the proposal as sent to the client. Returns the updated row."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if not row:
            return {"error": "Proposal not found"}
        if row.status != "done":
            return {"error": "Proposal must be generated before sending"}
        row.sentToClient = True
        row.sentAt = _now()
        row.updatedAt = _now()
        db.commit()
        return row.to_dict()


def save_inputs(project_id: str, inputs: Dict) -> Dict:
    """Store the admin-entered proposal fields (merged) and return the row.

    If the proposal has already been generated, the commercial table and reference
    are refreshed from the new inputs — prices, grouping and the reference are
    admin-owned, so they don't need an AI regeneration to take effect."""
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        if not row:
            row = ClientProposal(projectId=project_id, createdAt=_now())
            db.add(row)
        merged = dict(row.inputs or {})
        merged.update({k: v for k, v in (inputs or {}).items()})
        row.inputs = merged
        if row.content:
            row.content = _apply_admin_fields(project_id, row.content, merged)
        row.updatedAt = _now()
        db.commit()
        return row.to_dict()


def _to_number(v) -> float:
    """Parse an admin-entered amount ("1,200", "OMR 400", "") to a float."""
    import re
    s = re.sub(r"[^0-9.\-]", "", str(v or ""))
    try:
        return float(s) if s not in ("", "-", ".") else 0.0
    except ValueError:
        return 0.0


def _children(priced: list, group_index: int) -> list:
    """The sub-lines nested directly beneath the group header at `group_index`."""
    out = []
    for c in priced[group_index + 1:]:
        if not c["sub"]:
            break
        out.append(c)
    return out


def _costing_summary(project_id: str) -> dict:
    """The proposal's Cost Sheet rolled up for the client-facing costing lines.

    Returns one base line per activity (its name, work-hours and base cost) and the
    marked-up components — Contingency, Overheads, Profit, Income Tax and VAT — so
    the commercial table can list each as its own row. `hours`/`amount` carry the
    totals (total work-hours and the marked-up Suggested Pricing) for the no-detail
    fallback. Empty sheet → zeros / empty lists."""
    sheet = costing_service.get_sheet(project_id)
    activities = []
    for a in sheet.get("activities", []):
        a_hours = sum(float(e.get("hours") or 0) for e in a.get("entries", []))
        a_amount = float(a.get("total") or 0) or sum(
            float(e.get("hours") or 0) * float(e.get("rate") or 0)
            for e in a.get("entries", [])
        )
        if a_amount <= 0 and a_hours <= 0:
            continue
        activities.append({
            "name": str(a.get("description") or "").strip(),
            "hours": a_hours,
            "amount": a_amount,
        })

    s = sheet.get("summary") or {}
    markups = [
        {"item": "Contingency", "pct": float(s.get("contingencyPct") or 0), "amount": float(s.get("contingencyAmount") or 0)},
        {"item": "Overheads", "pct": float(s.get("overheadsPct") or 0), "amount": float(s.get("overheadsAmount") or 0)},
        {"item": "Profit", "pct": float(s.get("profitPct") or 0), "amount": float(s.get("profitAmount") or 0)},
        {"item": "Income Tax", "pct": float(s.get("incomeTaxPct") or 0), "amount": float(s.get("incomeTaxAmount") or 0)},
        {"item": "VAT", "pct": float(s.get("vatPct") or 0), "amount": float(s.get("vatAmount") or 0)},
    ]
    return {
        "hours": sum(x["hours"] for x in activities),
        "amount": float(s.get("suggestedPricing") or 0),
        "activities": activities,
        "markups": markups,
    }


def _apply_admin_commercials(content: dict, inputs: dict, costing=None) -> dict:
    """When the admin has priced the line items, use them verbatim as the costing
    (so the fees are exact, not AI-invented) and recompute the net total after any
    special discount.

    A group line (e.g. "Delay Analysis") carries no price of its own — it is priced
    by the sub-lines nested under it, and shows their subtotal.

    The 'Costing' line (flagged `costing`) is priced from the Cost Sheet and expands
    into several top-level rows: one base line per activity (its work-hours and base
    cost) followed by a line for each non-zero markup (Contingency, Overheads,
    Profit, Income Tax, VAT); a 0% markup such as VAT at 0% is omitted. With no Cost
    Sheet the single line is dropped unless a price was typed."""
    cost = costing or {}
    items = (inputs or {}).get("lineItems") or []

    priced = []
    for it in items:
        item = str(it.get("item", "")).strip()
        if not item:
            continue
        is_group = bool(it.get("group"))
        is_sub = bool(it.get("sub"))
        is_costing = bool(it.get("costing"))
        typed = str(it.get("amount", "")).strip()
        amount = _to_number(it.get("amount"))
        hours = None

        if is_costing:
            # The client-facing fee, sourced from the Cost Sheet. Expand it into one
            # base line per activity plus a line for each non-zero markup
            # (Contingency, Overheads, Profit, Income Tax, VAT), all top-level rows.
            activities = cost.get("activities") or []
            markups = cost.get("markups") or []
            if activities:
                base_desc = str(it.get("description", "")).strip()
                base_tl = str(it.get("timeline", "")).strip()
                for a in activities:
                    priced.append({
                        "item": str(a.get("name") or "").strip() or "Professional fee",
                        "description": base_desc,
                        "timeline": base_tl,
                        "amount": float(a.get("amount") or 0),
                        "group": False,
                        "sub": False,
                        "costing": True,
                        "hours": float(a.get("hours") or 0),
                    })
                for m in markups:
                    m_amount = float(m.get("amount") or 0)
                    if round(m_amount, 3) == 0:
                        continue  # hide zero / 0% markups (e.g. VAT at 0%)
                    priced.append({
                        "item": str(m.get("item") or "").strip(),
                        "description": "",
                        "timeline": "",
                        "amount": m_amount,
                        "group": False,
                        "sub": False,
                        "costing": True,
                    })
                continue  # expanded into rows above — skip the single-row append
            if not typed:
                continue  # no Cost Sheet and no typed price → omit the line
            # else: no sheet but a manual price was typed → keep one line below.
        elif is_sub and not typed:
            continue  # unpriced delay-event line → skip
        elif not is_group and not is_sub and not typed:
            continue  # unpriced top-level line → skip

        row = {
            "item": item,
            "description": str(it.get("description", "")).strip(),
            "timeline": str(it.get("timeline", "")).strip(),
            "amount": amount,
            "group": is_group,
            "sub": is_sub,
        }
        if is_costing:
            row["costing"] = True
        if hours is not None:
            row["hours"] = hours
        priced.append(row)

    # Drop a group header whose sub-lines were all skipped.
    priced = [
        c
        for i, c in enumerate(priced)
        if not c["group"] or (i + 1 < len(priced) and priced[i + 1]["sub"])
    ]
    for i, c in enumerate(priced):
        if c["group"]:
            c["amount"] = sum(s["amount"] for s in _children(priced, i))
    if not any(not c["group"] for c in priced):
        return content

    costing = list(priced)
    total = sum(c["amount"] for c in priced if not c["group"])
    discount = _to_number((inputs or {}).get("discount"))
    if discount > 0:
        costing.append(
            {
                "item": "Less special discount",
                "description": "",
                "timeline": "",
                "amount": -discount,
                "group": False,
                "sub": False,
            }
        )
        total -= discount

    content = dict(content)
    content["costing"] = costing
    content["total"] = total
    return content


def _apply_admin_fields(project_id: str, content: dict, inputs: dict) -> dict:
    """Overlay everything the admin owns onto a generated proposal: the exact
    prices and their grouping (with the Costing line priced from the Cost Sheet),
    and the assigned reference."""
    content = _apply_admin_commercials(content, inputs, _costing_summary(project_id))
    reference = str((inputs or {}).get("reference") or "").strip()
    if reference:
        content = {**content, "reference": reference}
    return content


def _load(project_id: str):
    """Blocking: gather proposal record, events, document names and admin inputs."""
    project = project_service.get_project(project_id)
    events = delay_event_service.list_by_project(project_id)
    doc_names = [d.get("name", "") for d in document_service.list_by_project(project_id)]
    with SessionLocal() as db:
        row = db.get(ClientProposal, project_id)
        inputs = dict(row.inputs) if row and row.inputs else {}
    return project, events, doc_names, inputs


async def run_generation(project_id: str) -> None:
    """Generate the costed client proposal in the background and store it."""
    async with _sem:
        _set(project_id, status="running", error=None)
        try:
            if not os.getenv("ANTHROPIC_API_KEY"):
                _set(project_id, status="failed", error=_NOT_CONFIGURED)
                return
            project, events, doc_names, inputs = await asyncio.to_thread(_load, project_id)
            if not project:
                _set(project_id, status="failed", error="Proposal not found.")
                return

            content = await generate_client_proposal(
                project=project, events=events, document_names=doc_names, inputs=inputs
            )
            # Admin-entered prices and reference are authoritative — they override
            # whatever the AI drafted.
            content = _apply_admin_fields(project_id, content, inputs)
            _set(project_id, content=content, model=MODEL, status="done", error=None)
        except anthropic.AuthenticationError:
            _set(project_id, status="failed", error=_NOT_CONFIGURED)
        except anthropic.APIStatusError as e:
            _set(project_id, status="failed", error=f"AI provider error ({e.status_code}).")
        except Exception as e:  # noqa: BLE001
            _set(project_id, status="failed", error=str(e)[:500])
