"""EOT claim document store + background generation (Proposal tab).

The claim is generated by AI from the project's delay events and documents, which
takes too long for an HTTP request — so generation runs in the background and the
row's `status` is polled by the UI. Blocking work runs in worker threads.
"""
import asyncio
import os
from datetime import datetime, timezone
from typing import Dict, Optional

import anthropic

from app.db import SessionLocal
from app.models import EOTClaim
from app.services import (
    admissibility_service,
    delay_event_service,
    document_service,
    methodology_service,
    project_clause_service,
    project_query_service,
    project_service,
)
from app.services.ai_service import MODEL, generate_eot_claim

_sem = asyncio.Semaphore(int(os.getenv("CLAIM_CONCURRENCY", "2")))

_NOT_CONFIGURED = (
    "AI analysis is not configured — set ANTHROPIC_API_KEY in apps/backend/.env "
    "and restart the backend."
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_claim(project_id: str) -> Dict:
    """Return the stored claim + status for a project (idle shape if none yet)."""
    with SessionLocal() as db:
        row = db.get(EOTClaim, project_id)
        return row.to_dict() if row else {
            "projectId": project_id, "content": None, "model": None,
            "status": "", "error": None, "updatedAt": None,
        }


def _set(project_id: str, **fields) -> None:
    with SessionLocal() as db:
        row = db.get(EOTClaim, project_id)
        if not row:
            row = EOTClaim(projectId=project_id, createdAt=_now())
            db.add(row)
        for k, v in fields.items():
            setattr(row, k, v)
        row.updatedAt = _now()
        db.commit()


def mark_running(project_id: str) -> None:
    _set(project_id, status="running", error=None)


def _load(project_id: str) -> Dict:
    """Blocking: gather every project module the claim is written from (run in a
    thread). The report draws on the same data the workspace tabs show — delay
    events, the Clause Library, admissibility, methodology, queries and the data
    room — so a section is only thin when the underlying tab is."""
    return {
        "project": project_service.get_project(project_id),
        "events": delay_event_service.list_by_project(project_id),
        "documents": document_service.list_by_project(project_id),
        "clauses": project_clause_service.list_by_project(project_id),
        "queries": project_query_service.list_by_project(project_id),
        # Stored assessments keep their status envelope; the claim only needs the
        # analyst-reviewed content.
        "admissibility": (admissibility_service.get(project_id) or {}).get("content"),
        "methodology": methodology_service.get_assessment(project_id),
    }


async def run_generation(project_id: str) -> None:
    """Generate the EOT claim in the background and store it."""
    async with _sem:
        _set(project_id, status="running", error=None)
        try:
            if not os.getenv("ANTHROPIC_API_KEY"):
                _set(project_id, status="failed", error=_NOT_CONFIGURED)
                return
            data = await asyncio.to_thread(_load, project_id)
            if not data.get("project"):
                _set(project_id, status="failed", error="Project not found.")
                return

            content = await generate_eot_claim(**data)
            _set(project_id, content=content, model=MODEL, status="done", error=None)
        except anthropic.AuthenticationError:
            _set(project_id, status="failed", error=_NOT_CONFIGURED)
        except anthropic.APIStatusError as e:
            _set(project_id, status="failed", error=f"AI provider error ({e.status_code}).")
        except Exception as e:  # noqa: BLE001
            _set(project_id, status="failed", error=str(e)[:500])
